#define RECIVE_BUFFER_SIZE 2048
#define MAX_COMMAND_NAME_LEN 20 
#define LOGIN_REQUEST_COMMAND "loginRequset"
#define LOGIN_RESPONSE_COMMAND "loginResponse"
#define USER_CHECK_REUQEST_COMMAND "userRequest"
#define USER_CHECK_RESPONSE_COMMAND "userResponse"
#define LOGIN_INVALID_USER_PASS 430

